---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for install
  become: yes
  stat:
    path: '{{ sshcode_install_dir }}'
  changed_when: False
  register: sshcode_binary
- when: not sshcode_binary.stat.exists
  block:
    - name: download
      become: yes
      become_user: root
      get_url:
        url: '{{ sshcode_url }}'
        dest: /tmp/{{ sshcode_tgz }}
        checksum: '{{ sshcode_checksum }}'
    - name: mkdir
      become: yes
      become_user: root
      file:
        path: '{{ sshcode_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchive
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: /tmp/{{ sshcode_tgz }}
        dest: '{{ sshcode_install_dir }}'
        creates: '{{ sshcode_install_exe }}'
  always:
    - name: cleanup
      become: yes
      become_user: root
      file:
        path: /tmp/{{ sshcode_tgz }}
        state: absent
- name: link dir
  become: yes
  become_user: root
  file:
    src: '{{ sshcode_install_dir }}'
    dest: '{{ sshcode_link_dir }}'
    state: link
- name: link exe
  become: yes
  become_user: root
  with_items:
    - sshcode
  file:
    src: '{{ sshcode_link_dir }}/{{ item }}'
    dest: '{{ sshcode_parent_install_dir }}/bin/{{ item }}'
    state: link
